export const LOGIN_PENDING = "LOGIN_PENDING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";

export const FETCH_USERS_PENDING = "FETCH_USERS_PENDING";
